# Generated by Django 5.0 on 2023-12-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about-pic-upload/')),
                ('image_title', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_text', models.CharField(blank=True, max_length=100)),
                ('primary_text', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HighlightsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='highlights-event/')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('event', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('details', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_icpep', models.ImageField(upload_to='logo-upload/')),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareTools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='software-tools/')),
            ],
        ),
    ]
