# Generated by Django 5.0.2 on 2024-03-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_highlightsevent_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlightsevent',
            name='learn_more',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
