# Generated by Django 5.0 on 2024-01-27 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_banner_primary_sub'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareToolsResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='software-resources/')),
                ('desc', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Logo',
        ),
        migrations.RemoveField(
            model_name='highlightsevent',
            name='event',
        ),
        migrations.AddField(
            model_name='highlightsevent',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='highlightsevent',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='highlightsevent',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='highlightsevent',
            name='details',
            field=models.CharField(blank=True, max_length=100, verbose_name='Hosted By'),
        ),
    ]
