# Generated by Django 5.0.2 on 2024-03-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_highlightsevent_learn_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwaretoolsresource',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
