# Generated by Django 5.0 on 2024-01-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_softwaretoolsresource_delete_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlightsevent',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
