# Generated by Django 5.0 on 2024-01-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_highlightsevent_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlightsevent',
            name='link_desc',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
