# Generated by Django 5.0 on 2024-01-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_highlightsevent_link_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlightsevent',
            name='link_desc',
            field=models.CharField(blank=True, default='Seize the opportunity and register your entry now on this link: ', max_length=255),
        ),
    ]
